name: selfnovel
description: SelfNovel
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^1.2.1
  file_picker: ^1.4.3+2
  dio: ^3.0.9
  encrypt: ^4.0.0
  url_launcher: ^5.4.10
  scrollable_positioned_list: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
