name: selfnovel
description: SelfNovel
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^1.2.1
  file_picker: ^1.4.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
